blank_issues_enabled: true
contact_links:
  - name: 🎨 Layout no Figma
    url: https://www.figma.com/design/eSQ2IVa6l7GrcpTSHO77RD/Banking-Frontend-Challenge-BR?node-id=0-1
    about: Telas, design system e protótipo navegável do desafio.
